FROM java:8-jre-alpine

ADD ./dist/PrivaliaSpringProject-0.0.1-SNAPSHOT.jar .
ADD ./dist/lib ./lib
CMD java -jar PrivaliaSpringProject-0.0.1-SNAPSHOT.jar
MAINTAINER "Javier Lllorente <javier.llorente@avanttic.com>" 